# # Pull latest official node image
# FROM node:latest
# # Expose ports
# EXPOSE 3000
# EXPOSE 35729
# # Set working directory
# WORKDIR /app
# # Add /app/node_modules/.bin to environment variables
# ENV PATH /app/node_modules/.bin:$PATH
# # Copy package files and install app dependencies
# COPY package.json /app/package.json
# COPY package-lock.json /app/package-lock.json
# RUN npm install
# RUN npm install react-scripts -g
# RUN npm install axios
# RUN npm install react-router-dom
# # Add React app to working directory
# ADD . /app
# # Start the React app
# CMD ["npm", "start"]


# Create image based on node image
FROM node:latest as build

# Set working directory
WORKDIR /frontend
COPY . /frontend
ENV REACT_APP_HOST_IP_ADDRESS $API_URL
ENV REACT_APP_BACKEND_URL $REACT_APP_BACKEND_URL

# Add /app/node_modules/.bin to environment variables
ENV PATH /frontend/node_modules/.bin:$PATH

# Install all app dependencies
COPY package.json /frontend/package.json
RUN npm install
COPY . ./
# Build the app
RUN npm run build
