
version: '3.7'

services:

    client:
        build:
            context: ./frontend
            dockerfile: dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks:
            - frontend

    mongodb:
        image: mongo:latest
        container_name: mongo
        hostname: test_mongodb
        environment:
            - MONGO_INITDB_DATABASE=animal_db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
        - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
        networks:
        - backend

    api:
        build: 
            context: ./backend
            dockerfile: dockerfile
        command: gunicorn --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        environment:
            - MONGO_INITDB_DATABASE=animal_db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
            - appdata:/var/www/
        depends_on: 
            - mongodb
        networks:
            - frontend
            - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local