version: '3.7'

services:

    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
            args:
                API_URL: "*"
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:5000
        volumes:
            - ./frontend/:/frontend
            - build_folder:/frontend/build
            - ./frontend/node_modules/:/frontend/node_modules
        tty: true

    # mongodb:
    #     image: mongo
    #     container_name: mongo
    #     restart: unless-stopped
    #     command: mongod --auth
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: "admin"
    #         MONGO_INITDB_ROOT_PASSWORD: "password"
    #         MONGO_INITDB_DATABASE: webapp
    #         MONGODB_DATA_DIR: /data/db
    #     volumes:
    #     - mongodbdata:/data/db
    #     networks:
    #     - backend

    backend:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn --bind 0.0.0.0:5000 app:app
        ports:
            - "5000:5000"
        volumes:
            - appdata:/var/www/
            - ./backend:/app
    nginx:
        build: ./nginx
        ports:
            - 80:8080
        volumes:
            - build_folder:/var/www/frontend
        depends_on:
            - backend
            - frontend



volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local
    build_folder: