
version: '3.7'

services:

    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        #networks:
        #    - frontend

    mongodb:
        image: mongo:latest
        container_name: mongo
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_DATABASE=animal_db
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
        - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

    backend:
        build: 
            context: ./backend
            dockerfile: dockerfile
        command: gunicorn --bind 0.0.0.0:5000 app:app --reload
        ports:
            - "5000:5000"
        environment:
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - MONGO_USER=root
            - MONGO_PASS=pass
            - MONGO_DATABASE=animal_db
        volumes:
            - appdata:/var/www/
            - ./backend:/app
        depends_on: 
            - mongodb

volumes:
    mongodb_data:
    appdata:
